declare default element namespace "http://www.sifassociation.org/au/datamodel/3.4";
for $d in .//StudentPersonal/AlertMessages/AlertMessage
return delete nodes $d,
for $d in .//StudentPersonal/AlertMessages/AlertMessage/@Type
return delete nodes $d,
for $d in .//StudentPersonal/MedicalAlertMessages/MedicalAlertMessage
return delete nodes $d,
for $d in .//StudentPersonal/StateProvinceId
return delete nodes $d,
for $d in .//StudentDailyAttendance/AttendanceCode
return delete nodes $d,
for $d in .//StudentDailyAttendance/AttendanceCode/Code
return delete nodes $d,
for $d in .//StudentDailyAttendance/AttendanceNote
return delete nodes $d,
for $d in .//StudentParticipation
return delete nodes $d//node(),
for $d in .//StudentPeriodAttendance/AttendanceCode
return delete nodes $d,
for $d in .//StudentPeriodAttendance/AttendanceCode/Code
return delete nodes $d,
for $d in .//StudentPeriodAttendance/AttendanceComment
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/InterventionOrder
return delete nodes $d,
for $d in .//StudentSDTN
return delete nodes $d//node(),
for $d in .//SummaryEnrollmentInfo
return delete nodes $d//node(),
for $d in .//AssessmentRegistration
return delete nodes $d//node(),
for $d in .//Identity
return delete nodes $d//node(),
for $d in .//StudentContactRelationship/ContactFlags/ParentLegalGuardian
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/PickupRights
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/LivesWith
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/AccessToRecords
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/ReceivesAssessmentReport
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/EmergencyContact
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/HasCustody
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/DisciplinaryContact
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/AttendanceContact
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/PrimaryCareProvider
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/FeesBilling
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/FamilyMail
return delete nodes $d,
for $d in .//StudentPersonal/GiftedTalented
return delete nodes $d,
for $d in .//StudentPersonal/EconomicDisadvantage
return delete nodes $d,
for $d in .//StudentPersonal/ESL
return delete nodes $d,
for $d in .//StudentPersonal/YoungCarersRole
return delete nodes $d,
for $d in .//StudentPersonal/Disability
return delete nodes $d,
for $d in .//StudentPersonal/IntegrationAide
return delete nodes $d,
for $d in .//StudentPersonal/PrePrimaryEducation
return delete nodes $d,
for $d in .//StudentSchoolEnrollment/ExitStatus/Code
return delete nodes $d,
for $d in .//StudentSchoolEnrollment/ExitType/Code
return delete nodes $d,
for $d in .//StudentSchoolEnrollment/RecordClosureReason
return delete nodes $d,
for $d in .//StudentSnapshot
return delete nodes $d//node(),
for $d in .//PersonInfo/Demographics/BirthDate
return delete nodes $d,
for $d in .//PersonInfo/Demographics/Religion/Code
return delete nodes $d,
for $d in .//PersonInfo/Demographics/ReligiousEventList/ReligiousEvent/Date
return delete nodes $d,
for $d in .//PersonInfo/Demographics/ReligiousRegion
return delete nodes $d,
for $d in .//PersonInfo/Demographics/VisaSubClass
return delete nodes $d,
for $d in .//PersonInfo/Demographics/VisaStatisticalCode
return delete nodes $d,
for $d in .//PersonInfo/Demographics/ImmunizationCertificateStatus
return delete nodes $d,
for $d in .//PersonInfo/Demographics/CulturalBackground
return delete nodes $d,
for $d in .//PersonInfo/AddressList
return delete nodes $d,
for $d in .//PersonInfo/PhoneNumberList
return delete nodes $d,
for $d in .//PersonPicture
return delete nodes $d//node(),
for $d in .//StaffPersonal/LocalId
return delete nodes $d,
for $d in .//StaffPersonal/StateProvinceId
return delete nodes $d,
for $d in .//StaffPersonal/ElectronidIdList
return delete nodes $d,
for $d in .//StaffPersonal/OtherIdList
return delete nodes $d,
for $d in .//StaffPersonal/EmploymentStatus
return delete nodes $d,
for $d in .//StudentContactPersonal/LocalId
return delete nodes $d,
for $d in .//StudentContactPersonal/OtherIdList
return delete nodes $d,
for $d in .//StudentContactPersonal/EmploymentType
return delete nodes $d,
for $d in .//StudentContactPersonal/SchoolEducationalLevel
return delete nodes $d,
for $d in .//StudentContactPersonal/NonSchoolEducation
return delete nodes $d,
for $d in .//StudentContactRelationship/@StudentPersonalRefId
return delete nodes $d,
for $d in .//StudentContactRelationship/@StudentContactPersonalRefId
return delete nodes $d,
for $d in .//StudentContactRelationship/StudentContactRelationshipRefId
return delete nodes $d,
for $d in .//StudentContactRelationship/Relationship/Code
return delete nodes $d,
for $d in .//StudentContactRelationship/ParentRelationshipStatus
return delete nodes $d,
for $d in .//StudentContactRelationship/HouseholdList
return delete nodes $d,
for $d in .//StudentContactRelationship/MainlySpeaksEnglishAtHome
return delete nodes $d,
for $d in .//StudentDailyAttendance/StudentPersonalRefId
return delete nodes $d,
for $d in .//StudentPeriodAttendance/AuditInfo/CreationUser/UserId
return delete nodes $d,
for $d in .//StudentPersonal/@RefId
return delete nodes $d,
for $d in .//StudentPersonal/LocalId
return delete nodes $d,
for $d in .//StudentPersonal/ElectronicIdList
return delete nodes $d,
for $d in .//StudentPersonal/OtherIdList
return delete nodes $d,
for $d in .//StudentPersonal/MostRecent/Parent1Language
return delete nodes $d,
for $d in .//StudentPersonal/MostRecent/Parent2Language
return delete nodes $d,
for $d in .//StudentPersonal/MostRecent/Parent1EmploymentType
return delete nodes $d,
for $d in .//StudentPersonal/MostRecent/Parent2EmploymentType
return delete nodes $d,
for $d in .//StudentPersonal/MostRecent/Parent1SchoolEducationLevel
return delete nodes $d,
for $d in .//StudentPersonal/MostRecent/Parent2SchoolEducationLevel
return delete nodes $d,
for $d in .//StudentPersonal/MostRecent/Parent1NonSchoolEducation
return delete nodes $d,
for $d in .//StudentPersonal/MostRecent/Parent2NonSchoolEducation
return delete nodes $d,
for $d in .//StudentSchoolEnrollment/IndividualLearningPlan
return delete nodes $d,
for $d in .//StudentSchoolEnrollment/PromotionInfo
return delete nodes $d,
for $d in .//StudentSchoolEnrollment/PromotionInfo/PromotionStatus
return delete nodes $d,
for $d in .//StudentScoreSet
return delete nodes $d//node(),
for $d in .//TeachingGroup/StudentList/TeachingGroupStudent/Name/FamilyName
return delete nodes $d,
for $d in .//TeachingGroup/StudentList/TeachingGroupStudent/Name/FullName
return delete nodes $d,
for $d in .//PersonInfo/Name/FamilyName
return delete nodes $d,
for $d in .//PersonInfo/Name/GivenName
return delete nodes $d,
for $d in .//PersonInfo/Name/MiddleName
return delete nodes $d,
for $d in .//PersonInfo/Name/PreferredGivenName
return delete nodes $d,
for $d in .//PersonInfo/Name/FullName
return delete nodes $d,
for $d in .//PersonInfo/OtherNames
return delete nodes $d,
for $d in .//PersonInfo/Demographics/IndigenousStatus
return delete nodes $d,
for $d in .//PersonInfo/Demographics/Sex
return delete nodes $d,
for $d in .//PersonInfo/Demographics/PlaceOfBirth
return delete nodes $d,
for $d in .//PersonInfo/Demographics/StateOfBirth
return delete nodes $d,
for $d in .//PersonInfo/Demographics/CountryOfBirth
return delete nodes $d,
for $d in .//PersonInfo/Demographics/CountriesOfCitizenship/CountryOfCitizenship
return delete nodes $d,
for $d in .//PersonInfo/Demographics/CountryArrivalDate
return delete nodes $d,
for $d in .//PersonInfo/Demographics/AustralianCitizenshipStatus
return delete nodes $d,
for $d in .//PersonInfo/Demographics/EnglishProficiency/Code
return delete nodes $d,
for $d in .//PersonInfo/Demographics/LanguageList/Language/Code
return delete nodes $d,
for $d in .//PersonInfo/Demographics/LanguageList/Language/LanguageType
return delete nodes $d,
for $d in .//PersonInfo/Demographics/DwellingArrangement/Code
return delete nodes $d,
for $d in .//PersonInfo/Demographics/PermanentResident
return delete nodes $d,
for $d in .//PersonInfo/Demographics/VisaExpiryDate
return delete nodes $d,
for $d in .//PersonInfo/Demographics/MaritalStatus
return delete nodes $d,
for $d in .//PersonInfo/EmailList
return delete nodes $d,
for $d in .//NOTHING
return replace value of node $d with 'ZZREDACTED'
