declare default element namespace "http://www.sifassociation.org/au/datamodel/3.4";
for $d in .//StudentPersonal/AlertMessages/AlertMessage
return delete nodes $d,
for $d in .//StudentPersonal/AlertMessages/AlertMessage/@Type
return delete nodes $d,
for $d in .//StudentPersonal/MedicalAlertMessages/MedicalAlertMessage
return delete nodes $d,
for $d in .//StudentPersonal/StateProvinceId
return delete nodes $d,
for $d in .//StudentDailyAttendance/AttendanceCode
return delete nodes $d,
for $d in .//StudentDailyAttendance/AttendanceCode/Code
return delete nodes $d,
for $d in .//StudentDailyAttendance/AttendanceNote
return delete nodes $d,
for $d in .//StudentParticipation
return delete nodes $d//node(),
for $d in .//StudentPeriodAttendance/AttendanceCode
return delete nodes $d,
for $d in .//StudentPeriodAttendance/AttendanceCode/Code
return delete nodes $d,
for $d in .//StudentPeriodAttendance/AttendanceComment
return delete nodes $d,
for $d in .//StudentContactRelationship/ContactFlags/InterventionOrder
return delete nodes $d,
for $d in .//StudentSDTN
return delete nodes $d//node(),
for $d in .//SummaryEnrollmentInfo
return delete nodes $d//node(),
for $d in .//NOTHING
return replace value of node $d with 'ZZREDACTED'
